### PR TITLE
Add cool badges to readme and stuff

### LINKED ISSUE #50: Add cool badges to README and stuff!

### PR DESCRIPTION
**Pull request by hoppjan**
fixes #50

- added build status
- added "Get it on Obtainium"
- fixed title

### CODE REVIEW

**Review by Importantus — COMMENTED** [review]
You could also add a version and licence badge. With this trinity of badges, I think it would look cool to center the title and maybe add a logo, too. You could take a look at the coinsaw repo to see what I mean. 

Two other purely optional ideas: Round the corners of the screenshot (you'd have to make it in the png itself) and move the install badge up into the introduction as the primary cta.

**Comment by hoppjan** [comment]
If you could do the image corners ;)

Otherwise I am done here :D

**Comment by hoppjan** [comment]
Centering feels weird

**Comment by Importantus** [comment]
Okay, I will edit the image and merge once I'm done 👍

**Review by Importantus — APPROVED** [review]

**Pull request merged**
